### ISSUE TITLE
Countdown

### ISSUE THREAD

**Issue by ScarlettCode** [jensstigaard/vinproma#1]
Hi,

This little app is amazing! Having what's on preview and the current clock is super helpful is a big studio setup! Can we had an option to have the clock countdown or show the countdown alongside the other times. I often need to count camera operators in so easier to have a counting down clock rather than a counting up

**Comment by jensstigaard** [comment]
Hi @ScarlettCode

What clock are you referring to? The Production Clock from inside vMix? With start time set?
If yes, then I will try and test out if I can see if it is possible to fetch from the vMix API - I have honestly not tried that before, but I can give it a go.
If not - can you elaborate a bit on what clock you expect to show? The time of day?

**Comment by ScarlettCode** [comment]
Hi @jensstigaard 

Sorry for the confusion. When I say clock I meant the timer of the current playing media. It currently shows 

(Current Time In Video / Total Video Time)

I'd like to add remaining time so 

(Current Time In Video / Total Video Time / Remaining Time)

Hope that makes sense?

**Comment by jensstigaard** [comment]
Hi @ScarlettCode 

Ah okay, yeah that makes totally sense. As it is already more or less presented for current playing media in preview or program in vMix.
I will make the update tonight. I will try and remember to comment this post whenever I have made the changes and pushed it as a release.

**Comment by jensstigaard** [comment]
Hi @ScarlettCode 

Just uploaded a new release with the desired changes.
Check out https://github.com/jensstigaard/vinproma/releases

Will close issue when confirmed working for you or after a few days without activity.

**Comment by ScarlettCode** [comment]
Used it during our production today and it was great! It's sometimes half a second fast or slow but think that's just the nature of it being over the network and web sockets. Thank you for the update!

**Comment by jensstigaard** [comment]
@ScarlettCode the current release is using a refresh frequency of 1000 ms (only once a second), meaning that what is shown can almost be "a second behind". The frequency can be changed to e.g. 300 ms, and thereby the delay will be much smaller, and the app will thereby be more accurate.

I will release a updated version tomorrow.

**Comment by jensstigaard** [comment]
@ScarlettCode I have now released version 0.3 which have lowered fetch interval to 200 ms. In my system I saw no major changes in CPU usage, and I found it suitable in regard to the latency experienced. https://github.com/jensstigaard/vinproma/releases

**Comment by jensstigaard** [comment]
@ScarlettCode any feedback on the changes?

**Comment by ScarlettCode** [comment]
Been using it and it's been great! Haven't noticed any issues so far! 

Thanks again

**Comment by jensstigaard** [comment]
Sounds good. I will close this issue now.
