### ISSUE TITLE
Colour key

### ISSUE THREAD

**Issue by macflo1508** [jensstigaard/vinproma#9]
Very nice tool. Works great for me.
Would it be possible to change the background colour in the html view to something like Green 255? Then we could key out the background in vMix.

**Comment by jensstigaard** [comment]
Do you use the HTML view as browser input inside vMix? It should automatically have transparent background..

**Comment by macflo1508** [comment]
> Do you use the HTML view as browser input inside vMix? It should automatically have transparent background..

I input the browser window into vmix as a NDI input, but as a local screenshare. Is that the wrong way?

**Comment by jensstigaard** [comment]
> > Do you use the HTML view as browser input inside vMix? It should automatically have transparent background..
> 
> I input the browser window into vmix as a NDI input, but as a local screenshare. Is that the wrong way?

I would recommend you using a direct Web Browser input in vMix. It supports transparant background. Use the direct link to the HTML view.
See this video
https://youtu.be/UqLHX4g3c8I

and this page
https://www.vmix.com/help24/WebBrowser.html

**Comment by macflo1508** [comment]
That works much better. Could have thought of that myself :-)
Thank's for the clarification.

**Comment by jensstigaard** [comment]
Good to hear 😄
